- src/main/java/PNUMEAT/Backend/domain/article/controller/ArticleController.java
- src/main/java/PNUMEAT/Backend/domain/article/dto/response/ArticleResponse.java
- src/main/java/PNUMEAT/Backend/domain/article/service/ArticleService.java
- src/main/java/PNUMEAT/Backend/domain/auth/entity/User.java
- src/main/resources/templates/article/detail.html
- src/main/resources/templates/article/edit.html
- src/main/resources/templates/article/list.html
- src/main/resources/templates/article/main.html
- src/main/resources/templates/article/new.html
- src/main/resources/templates/loginForm.html
- 이미지 수정 시 이미지 추가 안하면 기존 이미지로 유지, 새로운 이미지 추가하면 이미지 변경
- view 디자인 변경 (로그인, 메인, 글 자세히 보기)
> [스프린트 1] 강수민 - 수정 기능 변경, 전체적인 뷰 변경

- src/main/java/PNUMEAT/Backend/global/images/ImageService.java
- src/main/java/PNUMEAT/Backend/global/security/filter/JWTAccessFilter.java
- src/main/java/PNUMEAT/Backend/global/security/oauth/OAuth2UserServiceImpl.java
- src/main/java/PNUMEAT/Backend/global/security/resolver/CustomAuthenticationPrincipalArgumentResolver.java
- src/main/resources/application.properties
- src/main/resources/templates/article/main.html
개발 내용
- 불필요한 로그 삭제
- main 뷰 변경
> [스프린트 1] 장진영 - 간단한 파일 수정

- src/main/java/PNUMEAT/Backend/domain/article/controller/ArticleController.java
- src/main/java/PNUMEAT/Backend/domain/article/service/ArticleService.java
- src/main/resources/templates/article/main.html
- src/main/resources/templates/article/new.html
- 입력 없을 시 경고 발생
- 자신의 게시물 만 접근하도록 수정
close #12
> [스프린트 1] 강수민 - 입력 없을 시 경고 발생, 자신의 게시물 만 접근하도록 수정

- src/main/java/PNUMEAT/Backend/domain/article/controller/ArticleController.java
close #12 
- 사용하지 않는 컨트롤러를 삭제했습니다.
> refactor: 사용하지 않는 컨트롤러 삭제

- src/main/resources/application.properties
이미지 용량 10 -> 30mb로 수정했습니다
Closes #10 #13
> [스프린트 1] 박정우 - application.property 수정

- src/main/java/PNUMEAT/Backend/domain/article/service/ArticleService.java
close #17 
- 관리자가 모든 글을 볼 수 있도록 수정
> [스프린트 1] 관리자가 모든 글을 볼 수 있도록 수정

- src/main/java/PNUMEAT/Backend/domain/team/controller/TeamController.java
Resolves #36
- Team Controller 에서 api 명세대로 입력을 받지 않음
- Team Controller : createTeam 함수 내 MultiparFile value 수정
-
-
---
> [스프린트 3] 장진영 - #36 이슈 해결

- src/main/java/PNUMEAT/Backend/domain/auth/controller/AuthApiController.java
- src/main/java/PNUMEAT/Backend/global/security/oauth/OAuth2SuccessHandler.java
- src/main/java/PNUMEAT/Backend/global/security/utils/servletUtils/cookie/CookieUtils.java
Resolves #30
✏️ 변경 요약
Token 관련 기능 수정
🔍 작업 내용
1. cookie HttpOnly true, false 기능 추가
2. 재 로그인 시 기존 Refresh Token Update
📌 관련된 이슈
만약 로그인을 계속 시도한다면?....
📢 기타
> [스프린트 4] 장진영 - Refresh Token을 활용한 사용자 경험 개선 기능 추가

- src/main/java/PNUMEAT/Backend/domain/auth/entity/Member.java
- src/main/java/PNUMEAT/Backend/domain/team/entity/Team.java
- src/main/java/PNUMEAT/Backend/domain/teamMember/entity/TeamMember.java
- 지연 로딩 설정을 잘못했습니다.
- ManyToOne에 지연로딩을 설정했습니다. 
- 지연 로딩 설정 제대로 되어있는지 확인해주세요!
-
---
> [스프린트 4] fetch 설정 수정스프린트 4] Lazy 설정 수정

- src/main/java/PNUMEAT/Backend/domain/auth/entity/Member.java
- member update시 공백 일 때 member 정보 수정된다.
- isEmpty method 적용
-
-
---
> [스프린트 4] 장진영 - 회원 프로필 버그 수정

- src/main/java/PNUMEAT/Backend/domain/team/controller/TeamController.java
- src/main/java/PNUMEAT/Backend/domain/team/dto/response/MyTeamResponse.java
- src/main/java/PNUMEAT/Backend/domain/team/dto/response/TeamAllResponse.java
- src/main/java/PNUMEAT/Backend/domain/team/dto/response/TeamCombinedResponse.java
- src/main/java/PNUMEAT/Backend/domain/team/entity/Team.java
- src/main/java/PNUMEAT/Backend/domain/team/repository/TeamRepository.java
- src/main/java/PNUMEAT/Backend/domain/team/service/TeamService.java
- src/main/java/PNUMEAT/Backend/domain/teamMember/entity/TeamMember.java
- src/main/java/PNUMEAT/Backend/domain/teamMember/repository/TeamMemberRepository.java
- src/main/java/PNUMEAT/Backend/global/response/ResponseMessageEnum.java
- src/main/java/PNUMEAT/Backend/global/security/configuration/JpaAuditingConfiguration.java
- src/main/java/PNUMEAT/Backend/global/security/configuration/WebConfig.java
- src/test/java/PNUMEAT/Backend/domain/team/repository/TeamRepositoryTest.java
- src/test/java/PNUMEAT/Backend/domain/team/service/TeamServiceTest.java
- src/test/java/PNUMEAT/Backend/domain/teamMember/repository/TeamMemberRepositoryTest.java
1. 나의 팀 조회 API 생성
2. 전체 팀 조회 API 생성
3. 나의 팀 & 전체 팀 조회 API 생성
위와 동일
Resolves #21 
리팩토링 할 부분 있으면 알려주세요!
테스트 케이스 given 부분이 너무 복잡해서 리팩토링 할 방법을 고민 중입니다.
---
> [스프린트 4] 강수민 - 팀 조회하기 API 구현

- src/main/java/PNUMEAT/Backend/domain/team/controller/TeamController.java
- src/main/java/PNUMEAT/Backend/domain/team/dto/request/TeamJoinRequest.java
- src/main/java/PNUMEAT/Backend/domain/team/service/TeamService.java
- src/main/java/PNUMEAT/Backend/domain/teamMember/repository/TeamMemberRepository.java
- src/main/java/PNUMEAT/Backend/global/error/ErrorCode.java
- src/main/java/PNUMEAT/Backend/global/error/Team/TeamAlreadyJoinException.java
- src/main/java/PNUMEAT/Backend/global/error/Team/TeamNotFoundException.java
- src/main/java/PNUMEAT/Backend/global/error/Team/TeamPasswordInvalidException.java
- src/main/java/PNUMEAT/Backend/global/response/ResponseMessageEnum.java
- src/main/resources/application.properties
- src/test/java/PNUMEAT/Backend/domain/team/service/TeamServiceTest.java
팀 가입하기 API를 만들었습니다.
1. 팀 가입하기 api 구현
2. 팀 가입하기 api 테스트 코드 작성
Resolves #21 
없습니다.
---
> [스프린트 4] 강수민 - 팀 가입하기 API 구현

- src/main/java/PNUMEAT/Backend/domain/team/service/TeamService.java
자신의 팀이 있는 경우, 다른 팀에 가입 못하는 버그 수정
1. join team에 Transactional 추가
Resolves #21 
...
---
> [스프린트 4] 강수민 - 팀 가입 오류 해결

- src/main/java/PNUMEAT/Backend/domain/article/controller/ArticleController.java
- src/main/java/PNUMEAT/Backend/domain/article/dto/request/ArticleRequest.java
- src/main/java/PNUMEAT/Backend/domain/article/dto/response/ArticleResponse.java
- src/main/java/PNUMEAT/Backend/domain/article/entity/Article.java
- src/main/java/PNUMEAT/Backend/domain/article/entity/ArticleImage.java
- src/main/java/PNUMEAT/Backend/domain/article/enums/ArticleCategory.java
- src/main/java/PNUMEAT/Backend/domain/article/enums/ArticleStatus.java
- src/main/java/PNUMEAT/Backend/domain/article/repository/ArticleImageRepository.java
- src/main/java/PNUMEAT/Backend/domain/article/repository/ArticleRepository.java
- src/main/java/PNUMEAT/Backend/domain/article/service/ArticleService.java
- src/main/java/PNUMEAT/Backend/global/error/articles/ArticleNotFoundException.java
- src/main/java/PNUMEAT/Backend/global/images/ImageConstant.java
- src/main/java/PNUMEAT/Backend/global/images/ImageService.java
- src/main/java/PNUMEAT/Backend/global/response/ResponseMessageEnum.java
- src/test/java/PNUMEAT/Backend/domain/article/service/ArticleServiceTest.java
게시물 작성
자신이 쓴 게시물 조회
특정 팀의 게시물 조회
특정 게심물 조회
게시물 삭제
게시물 수정
검증로직을 넣어야하나 고민된다.
> [스프린트 4] 박정우 - 게시물 작성 로직 완성

- src/main/java/PNUMEAT/Backend/domain/article/controller/ArticleController.java
- src/main/java/PNUMEAT/Backend/domain/article/entity/Article.java
- src/main/java/PNUMEAT/Backend/domain/article/entity/ArticleImage.java
- src/main/java/PNUMEAT/Backend/domain/article/repository/ArticleRepository.java
- src/main/java/PNUMEAT/Backend/domain/article/service/ArticleService.java
- src/main/java/PNUMEAT/Backend/domain/teamMember/repository/TeamMemberRepository.java
- src/main/java/PNUMEAT/Backend/global/error/ErrorCode.java
- src/main/java/PNUMEAT/Backend/global/error/articles/MemberNotInTeamException.java
- src/main/java/PNUMEAT/Backend/global/error/articles/UnauthorizedActionException.java
- src/test/java/PNUMEAT/Backend/domain/article/repository/ArticleRepositoryTest.java
- src/test/java/PNUMEAT/Backend/domain/article/service/ArticleServiceTest.java
모든 api 검증로직 추가
1. 날짜기준 게시글 가져오기 구현
2. 검증로직 추가
...
---
> [스프린트 4] 박정우 - 게시글 기능 API 구현 

- src/main/java/PNUMEAT/Backend/domain/article/controller/ArticleController.java
- src/main/java/PNUMEAT/Backend/domain/article/dto/request/ArticleRequest.java
- src/main/java/PNUMEAT/Backend/domain/article/dto/response/ArticleResponse.java
- src/main/java/PNUMEAT/Backend/domain/article/entity/Article.java
- src/main/java/PNUMEAT/Backend/domain/article/enums/ArticleCategory.java
- src/main/java/PNUMEAT/Backend/domain/article/service/ArticleService.java
- src/test/java/PNUMEAT/Backend/domain/article/repository/ArticleRepositoryTest.java
- src/test/java/PNUMEAT/Backend/domain/article/service/ArticleServiceTest.java
- src/test/resources/application.properties
게시글 작성 요청 및 응답 양식을 수정했습니다.
1. 게시글 작성 요청에서 게시글 카테고리를 제거했습니다.
2. 게시글 응답 요청에서 게시글 카테고리를 제거했습니다.
Resolves #55 
...
---
> [스프린트 5] 강수민 - 게시글 작성 요청 수정

- src/main/java/PNUMEAT/Backend/domain/article/controller/ArticleController.java
- src/main/java/PNUMEAT/Backend/domain/article/dto/request/CalenderSubjectRequest.java
- src/main/java/PNUMEAT/Backend/domain/article/dto/response/CalenderSubjectResponse.java
- src/main/java/PNUMEAT/Backend/domain/article/dto/response/SubjectArticleDateAndTagResponse.java
- src/main/java/PNUMEAT/Backend/domain/article/repository/ArticleRepository.java
- src/main/java/PNUMEAT/Backend/domain/article/service/ArticleService.java
- src/test/java/PNUMEAT/Backend/domain/article/repository/ArticleRepositoryTest.java
팀장 페이지 기능 구현
1. 년도, 월을 바탕으로 Subject Article 태그 반환
2. 팀 공지사항 내용 반환
Resolves #58 
...
---
>  [스프린트 5] 장진영 - 팀장 페이지 기능 구현

- src/main/java/PNUMEAT/Backend/domain/article/controller/ArticleController.java
- src/main/java/PNUMEAT/Backend/domain/article/dto/response/ArticleResponse.java
- src/main/java/PNUMEAT/Backend/domain/team/controller/TeamController.java
- src/main/java/PNUMEAT/Backend/domain/team/dto/response/TeamJoinResponse.java
- src/test/java/PNUMEAT/Backend/domain/article/repository/ArticleRepositoryTest.java
- src/test/java/PNUMEAT/Backend/domain/article/service/ArticleServiceTest.java
게시물 조회 api 수정 및  article service 테스트 이름 수정
1. 팀 게시물 조회 시, 페이지네이션 개수 수정
2. 팀 게시물 조회 시, 생성일 출력 형식 수정
3. article service 테스트명 변경
...
---
> [스프린트 5] 강수민 - 팀 게시물 조회 기능 수정 및 테스트 이름 수정

- src/main/java/PNUMEAT/Backend/domain/article/dto/response/CalenderSubjectResponse.java
- src/main/java/PNUMEAT/Backend/domain/article/service/ArticleService.java
팀 페이지 응답에서 팀 매니저 여부 필드 응답 API에 추가
1. 팀 페이지 응답에서 팀 매니저 여부 필드 응답 API에 추가
...
---
> [스프린트 5] 팀 페이지 응답 수정

- src/main/java/PNUMEAT/Backend/domain/article/controller/ArticleController.java
- src/main/java/PNUMEAT/Backend/domain/article/service/ArticleService.java
- src/main/java/PNUMEAT/Backend/domain/team/controller/TeamController.java
- src/main/java/PNUMEAT/Backend/domain/team/dto/response/TeamPageResponse.java
API Path 수정
"teams/{teamId}/subjects/calender -> /{teamId}/team-page 수정 
1.  teams/{teamId}/subjects/calender -> /{teamId}/team-page 수정
> [스프린트 5] 장진영 - API Path 수정

- src/main/java/PNUMEAT/Backend/domain/article/controller/ArticleController.java
- src/main/java/PNUMEAT/Backend/domain/auth/controller/MemberController.java
- src/main/java/PNUMEAT/Backend/domain/team/controller/TeamController.java
- src/main/java/PNUMEAT/Backend/global/error/dto/response/ApiResponse.java
팀 가입 시, 데이터와 메시지 동시에 가도록 수정
1. 팀 가입 시, 데이터와 메시지 동시에 가도록 수정
...
---
> [스프린트 5] - 강수민 팀 가입 시, 데이터와 메시지 동시에 가도록 수정

- src/main/java/PNUMEAT/Backend/domain/article/controller/ArticleController.java
- src/main/java/PNUMEAT/Backend/domain/article/dto/response/TeamSubjectResponse.java
팀 주제 조회 API 수정
1. 팀 주제 조회 시 작성자 이름 및 사진 뜨도록 수정
...
---
> [스프린트 5] 강수민 - 팀 주제 조회 API 수정

- src/main/java/PNUMEAT/Backend/domain/article/controller/ArticleController.java
- src/main/java/PNUMEAT/Backend/domain/article/dto/response/ArticleResponse.java
- src/main/java/PNUMEAT/Backend/domain/article/repository/ArticleRepository.java
- src/main/java/PNUMEAT/Backend/domain/article/service/ArticleService.java
- src/test/java/PNUMEAT/Backend/domain/article/repository/ArticleRepositoryTest.java
- src/test/java/PNUMEAT/Backend/domain/article/service/ArticleServiceTest.java
...
1. sql 수정
2. 멤버 사진 , 멤버 이름 dto 추가
...
---
> [스프린트 5] 박정우 - 팀 게시글 조회 정보 추가

- src/test/java/PNUMEAT/Backend/domain/article/repository/ArticleRepositoryTest.java
- src/test/java/PNUMEAT/Backend/domain/article/service/ArticleServiceTest.java
...
1.테스트 코드 작성
바보짓하고있었음
...
---
> [스프린트 5] 박정우 - 팀 게시글 조회 테스트코드 추가
